version: '3'
services:
  postgres:
    image: postgres:14.3
    container_name: postgres-pomodoro
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
