version: '3'
services:
  postgres:
    image: postgres:14.3
    container_name: postgres-pomodoro
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: pomodoro-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL:      ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET:                 ${JWT_SECRET}
      JWT_EXPIRATION_TIME:        ${JWT_EXPIRATION_TIME}
    depends_on:
      - postgres
volumes:
  postgres-data:
