spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pomodoro
    username: pomodoro
    password: ${pomodoro.db.password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml