application:
  title: PomodoroApp
  version: 1.0.0

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

jwt:
  expiration:
    time: ${JWT_EXPIRATION_TIME:1800000}
  secret: ${JWT_SECRET}
