spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/pomodoro
    username: pomodoro
    password: pomodoro
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/integration/db.changelog-integration.xml
    contexts: integration
