spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/pomodoro
    username: pomodoro
    password: pomodoro
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
