spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/pomodoro
    username: pomodoro
    password: pomodoro
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/integration/db.changelog-integration.xml
    contexts: integration

jwt:
  expiration:
    time: 1800000
  secret: '357638792F423F4428472B4B6250655368566D597133743677397A2443264628'
