DROP TABLE IF EXISTS PUBLIC.DATABASECHANGELOGLOCK;
DROP TABLE IF EXISTS PUBLIC.DATABASECHANGELOG;
DROP TABLE IF EXISTS PUBLIC.TASKS;
DROP TABLE IF EXISTS PUBLIC.USERS_ROLES;
DROP TABLE IF EXISTS PUBLIC.ROLES;
DROP TABLE IF EXISTS PUBLIC.USERS;
